# @package _global_
# changes hyper-parameters of model if resnet-50 used with cifar-100
# more info: https://hydra.cc/docs/patterns/specializing_config
model:
  num_classes: 100

hparams:
  epochs: 200
  batch_size: 128
  grad_clip_max_norm: 5 # change to float to activate

  optimizer:
    _target_: torch.optim.SGD
    lr: 0.1
    weight_decay: 1e-5
    momentum: 0.9
    nesterov: false

  # scheduler:
  #   _target_: torch.optim.lr_scheduler.MultiStepLR
  #   milestones: [80, 120]
  #   gamma: 0.01

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 200
    eta_min: 0

