# @package _global_
# changes hyper-parameters of model if resnet-50 used with cifar-10
# more info: https://hydra.cc/docs/patterns/specializing_config

hparams:
  epochs: 10
  batch_size: 128
  grad_clip_max_norm: null # change to float to activate

  optimizer:
    _target_: torch.optim.SGD
    lr: 0.001
    weight_decay: 1e-3
    momentum: 0.9
    nesterov: False

  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [5, 10]
    gamma: 0.1
