# @package _global_
# changes hyper-parameters of model if resnet-50 used with cifar-100
# more info: https://hydra.cc/docs/patterns/specializing_config
hparams:
  epochs: 120
  batch_size: 128
  grad_clip_max_norm: 5 # change to float to activate

  optimizer:
    _target_: torch.optim.SGD
    lr: 0.1
    weight_decay: 1e-3
    momentum: 0.9
    nesterov: true

  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [40, 80]
    gamma: 0.01
